config/routes.rb
Rails.application.routes.draw do
  resources :prayers
  root to: 'home#front'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prayer.rb
class Prayer < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: {maximum: 5000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable
   
  validates :fullname, presence: true, length: {maximum: 50}

  has_many :prayer

  def self.from_omniauth(auth)
      user = User.where(email: auth.info.email).first

      if user
        return user
      else
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
          user.email = auth.info.email
          user.password = Devise.friendly_token[0,20]
          user.fullname = auth.info.name
          user.image = auth.info.image
          user.uid = auth.uid
          user.provider = auth.provider

          # If you are using confirmable and the provider(s) you use validate emails,
          # uncomment the line below to skip the confirmation emails.
          user.skip_confirmation!
        end
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :description])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def front
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  before_action :set_prayer, only: [:show, :edit, :update, :destroy]

 def index
  @prayers = Prayer.all
 
  respond_to do |format|
    format.html  # index.html.erb
    format.json  { render :json => @prayers }
  end
end

  def show
  @prayer = Prayer.find(params[:id])
 
  respond_to do |format|
    format.html  # show.html.erb
    format.json  { render :json => @prayer }
  end
end

  def new
  @prayer = Prayer.new
 
  respond_to do |format|
    format.html  # new.html.erb
    format.json  { render :json => @prayer }
  end
end

  def edit
  @prayer = Prayer.find(params[:id])
end

def create
  @prayer = current_user.prayer.build(prayer_params)
 
  respond_to do |format|
    if @prayer.save
      format.html  { redirect_to(@prayer,
                    :notice => 'Prayer was successfully created.') }
      format.json  { render :json => @prayer,
                    :status => :created, :location => @prayer }
    else
      format.html  { render :action => "new" }
      format.json  { render :json => @prayer.errors,
                    :status => :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /prayers/1
  # PATCH/PUT /prayers/1.json
  def update
    respond_to do |format|
      if @prayer.update(prayer_params)
        format.html { redirect_to @prayer, notice: 'Prayer was successfully updated.' }
        format.json { render :show, status: :ok, location: @prayer }
      else
        format.html { render :edit }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prayers/1
  # DELETE /prayers/1.json
  def destroy
    @prayer.destroy
    respond_to do |format|
      format.html { redirect_to prayers_url, notice: 'Prayer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prayer
      @prayer = Prayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prayer_params
      params.require(:prayer).permit(:content, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image
      "http://graph.facebook.com/#{user.uid}/picture?type=large"
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/views/home/front.html.erb
<h1>Home#front</h1>
<p>Find me in app/views/home/front.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Behold</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/hot-sneaks/jquery-ui.css">
  </head>

  <body>

   <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>
    
    <%= yield %>
  </body>
</html>

app/views/prayers/_form.html.erb
<%= form_for(@prayer) do |f| %>
  <div class="form-group">
    <%= f.label 'Update Prayer' %><br>
      <%= f.text_area :content, class: 'form-control', autofocus: true, 
          placeholder: 'Type your prayer here' %>
  </div>
  <%= f.submit :prayer, class: 'btn btn-primary'%>
<% end %>

app/views/prayers/edit.html.erb
<h1>Editing Prayer</h1>

<%= render 'form', prayer: @prayer %>

<%= link_to 'Show', @prayer %> |
<%= link_to 'Back', prayers_path %>

app/views/prayers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prayers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prayers.each do |prayer| %>
      <tr>
        <td><%= prayer.content %></td>
        <td><%= prayer.user %></td>
        <td><%= link_to 'Show', prayer %></td>
        <td><%= link_to 'Edit', edit_prayer_path(prayer) %></td>
        <td><%= link_to 'Destroy', prayer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prayer', new_prayer_path %>

app/views/prayers/new.html.erb
<h1>New Prayer</h1>

<%= render 'form', prayer: @prayer %>

<%= link_to 'Back', prayers_path %>

app/views/prayers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @prayer.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @prayer.user.fullname %>
</p>

<%= link_to 'Edit', edit_prayer_path(@prayer) %> |
<%= link_to 'Back', prayers_path %>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Behold", root_path, class: "navbar-brand" %>
    </div>
      <ul class="nav navbar-nav navbar-right">
        
        <% if (!user_signed_in?) %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                    role="button" aria-haspopup="true" aria-expanded="false">
                    <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
                    <%= current_user.fullname %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li role="separator" class="divider"></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Prayer Request", prayers_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>